// 移行検証用ルート一覧（出典: src/App.jsx PAGE_META — 全35ルート）
export const ROUTES = [
  '/',
  '/lab-takeshima',
  '/lab-kamoshita',
  '/lab-kunii',
  '/lab-iimura',
  '/lab-kamiyama',
  '/lab-ishii',
  '/lab-komeichi',
  '/lab-nakaoka',
  '/lab-shibasaki',
  '/lab-yamazaki',
  '/lab-niikura',
  '/lab-okamoto',
  '/koudai-project',
  '/kokushi-report',
  '/student-column-1',
  '/event-0531',
  '/student-column-3',
  '/lab-kamiyama-report',
  '/lab-takeshima-column',
  '/eiyo-app-report',
  '/news',
  '/features',
  '/qualifications',
  '/support',
  '/career',
  '/campus-life',
  '/voices',
  '/faq',
  '/sports-nutrition',
  '/sports-nutrition-health',
  '/kotosupport',
  '/submajor',
  '/columns',
  '/living-alone',
];

export const routeSlug = (route) => (route === '/' ? 'home' : route.slice(1).replace(/\//g, '_'));
